name: Append to CHANGELOG on Push to Main

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate new changelog entry from latest commit
        run: |
          REPO_URL="https://github.com/${{ github.repository }}"

          echo "## $(date +'%Y-%m-%d')" > NEW_CHANGELOG.md
          echo "" >> NEW_CHANGELOG.md

          git log -1 --pretty=format:"%h|%s|%an" | while IFS='|' read -r sha message author; do
            if [ -n "$message" ]; then
              echo "- ${message} ([\`${sha}\`](${REPO_URL}/commit/${sha}) by ${author})" >> NEW_CHANGELOG.md
            fi
          done

          echo "" >> NEW_CHANGELOG.md
          cat CHANGELOG.md >> NEW_CHANGELOG.md || true
          mv NEW_CHANGELOG.md CHANGELOG.md

      - name: Commit and push if changelog changed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          if ! git diff --quiet; then
            git add CHANGELOG.md
            git commit -m "chore: update changelog on push to main"
            git push origin HEAD:${{ github.event.repository.default_branch }}
          else
            echo "No changes to changelog."
          fi
