name: Append to CHANGELOG on Tag Push

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get previous tag
        id: get_tag
        run: |
          echo "current=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
          prev=$(git describe --tags --abbrev=0 HEAD^)
          echo "previous=$prev" >> $GITHUB_OUTPUT

      - name: Generate changelog section
        run: |
          TAG=${{ steps.get_tag.outputs.current }}
          PREV_TAG=${{ steps.get_tag.outputs.previous }}
          DATE=$(date +"%Y-%m-%d")
          echo "## $TAG - $DATE" > NEW_CHANGELOG.md
          echo "" >> NEW_CHANGELOG.md
          git log $PREV_TAG..HEAD --pretty=format:"- %s" >> NEW_CHANGELOG.md
          echo "" >> NEW_CHANGELOG.md
          cat CHANGELOG.md >> NEW_CHANGELOG.md || true
          mv NEW_CHANGELOG.md CHANGELOG.md

      - name: Show git status and diff (for debugging)
        run: |
          git status
          git diff || echo "No diff"

      - name: Commit and push changelog if changed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          if ! git diff --quiet; then
            git add CHANGELOG.md
            git commit -m "chore: update changelog for ${{ steps.get_tag.outputs.current }}"
            git push origin HEAD:${{ github.event.repository.default_branch }}
          else
            echo "No changes to commit"
          fi
